option cplex_options 'primal integrality = 2e-09 mipgap=0.05'; #mipemphasis=1
solve ;

display fun_obj ;
display sum{d in D, h in H} B[d,h] ;
display sum{d in D, h in H} HUNDER[d,h];
display sum{d in D, h in H} HOVER[d,h];



#display B;
display {d in D} sum{h in H} HUNDER[d,h];
display {d in D} sum{h in H} HOVER[d,h];

display {h in H} sum{d in D} B[d,h];
display {h in H} sum{d in DLUVI} B[d,h];
display {h in H} sum{d in DSADO} B[d,h];

